# Basic Information 
title: Hong Seok Kim
position: Ph.D. Student
affiliation: Iowa State University
affiliation_link: https://econ.iastate.edu/
affiliation_logo: ./assets/img/iowa_state_logo.jpeg
email: hongseok (at) iastate.edu

# Search Engine Optimization (SEO)
keywords: hongseok kim, kim hongseok, hongseokimm, hongseokkim
canonical: https://www.econ.iastate.edu/
description: Hongseok Kim is a Ph.D. student in Economics at the Iowa State University. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/
twitter: https://twitter.com/

# Images 
avatar: ./assets/img/hongseok.png
favicon: ./assets/img/iowastate.png
favicon_dark: ./assets/img/iowastate.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
